import { FiEdit2, FiTrash2 } from 'react-icons/fi';
import { formatBudget } from '../../utils/weddingFormat.js';

const statusStyles = { planned: 'bg-stone-100 text-stone-600', partially_paid: 'bg-amber-50 text-amber-700', paid: 'bg-emerald-50 text-emerald-700' };
const statusLabels = { planned: 'Planned', partially_paid: 'Partially Paid', paid: 'Paid' };

function Difference({ item }) {
  const difference = item.plannedAmount - item.actualAmount;
  return difference < 0 ? <span className="font-medium text-red-600">{formatBudget(Math.abs(difference))} over</span> : <span className="text-stone-600">{formatBudget(difference)}</span>;
}

function Actions({ item, onEdit, onDelete, deleting }) {
  return <div className="flex items-center gap-1"><button type="button" onClick={() => onEdit(item)} className="rounded-lg p-2 text-stone-500 hover:bg-brand-50 hover:text-brand-700" aria-label={`Edit ${item.title}`}><FiEdit2 /></button><button type="button" disabled={deleting === item._id} onClick={() => onDelete(item)} className="rounded-lg p-2 text-stone-500 hover:bg-red-50 hover:text-red-600 disabled:opacity-50" aria-label={`Delete ${item.title}`}><FiTrash2 /></button></div>;
}

function BudgetItemList({ items, onEdit, onDelete, deleting }) {
  return <><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b bg-stone-50 text-xs uppercase tracking-wide text-stone-400"><th className="px-5 py-4 font-semibold">Category</th><th className="px-5 py-4 font-semibold">Item</th><th className="px-5 py-4 font-semibold">Planned</th><th className="px-5 py-4 font-semibold">Spent</th><th className="px-5 py-4 font-semibold">Difference</th><th className="px-5 py-4 font-semibold">Status</th><th className="px-5 py-4 font-semibold">Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item._id} className="border-b last:border-0"><td className="px-5 py-4"><span className="rounded-full bg-brand-50 px-3 py-1 text-xs font-medium text-brand-700">{item.category}</span></td><td className="px-5 py-4"><p className="font-semibold text-stone-800">{item.title}</p>{item.notes && <p className="mt-1 max-w-52 truncate text-xs text-stone-400">{item.notes}</p>}</td><td className="px-5 py-4 font-medium text-stone-700">{formatBudget(item.plannedAmount)}</td><td className="px-5 py-4 font-medium text-stone-700">{formatBudget(item.actualAmount)}</td><td className="px-5 py-4"><Difference item={item} /></td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${statusStyles[item.status]}`}>{statusLabels[item.status]}</span></td><td className="px-5 py-4"><Actions item={item} onEdit={onEdit} onDelete={onDelete} deleting={deleting} /></td></tr>)}</tbody></table></div><div className="space-y-4 p-4 md:hidden">{items.map((item) => <article key={item._id} className="rounded-2xl border border-stone-100 p-5"><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-brand-50 px-3 py-1 text-xs font-medium text-brand-700">{item.category}</span><h3 className="mt-3 font-semibold text-stone-900">{item.title}</h3></div><Actions item={item} onEdit={onEdit} onDelete={onDelete} deleting={deleting} /></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-stone-400">Planned</p><p className="mt-1 font-semibold">{formatBudget(item.plannedAmount)}</p></div><div><p className="text-xs text-stone-400">Spent</p><p className="mt-1 font-semibold">{formatBudget(item.actualAmount)}</p></div><div><p className="text-xs text-stone-400">Difference</p><p className="mt-1"><Difference item={item} /></p></div><div><p className="text-xs text-stone-400">Status</p><span className={`mt-1 inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${statusStyles[item.status]}`}>{statusLabels[item.status]}</span></div></div>{item.notes && <p className="mt-4 border-t pt-4 text-sm leading-6 text-stone-500">{item.notes}</p>}</article>)}</div></>;
}
export default BudgetItemList;
