import 'dotenv/config'; import mongoose from 'mongoose'; import BudgetItem from '../src/models/BudgetItem.js'; import Guest from '../src/models/Guest.js'; import Task from '../src/models/Task.js'; import User from '../src/models/User.js'; import Wedding from '../src/models/Wedding.js';
const base=process.env.API_BASE_URL||'http://localhost:5000/api/v1',stamp=Date.now(),users=[];let passed=0;
async function req(path,{token,method='GET',body,status=200}={}){const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json().catch(()=>({}));if(response.status!==status)throw new Error(`${method} ${path}: expected ${status}, got ${response.status}: ${data.message}`);return data;}
function pass(name,condition=true){if(!condition)throw new Error(name);passed++;console.log(`PASS: ${name}`)}
async function register(label){const data=await req('/auth/register',{method:'POST',status:201,body:{firstName:label,lastName:'MultiTest',email:`${label}-${stamp}@test.local`,password:'MultiWedding123!',role:'customer'}});users.push(data.user._id);return data;}
const wedding=(name,date,city)=>({weddingName:name,partner1Name:name.split(' ')[0],partner2Name:name.split(' ')[1],weddingDate:date,city,estimatedBudget:10000,expectedGuests:100});
try{const[a,b]=await Promise.all([register('CustomerA'),register('CustomerB')]);const a1=(await req('/weddings',{token:a.token,method:'POST',status:201,body:wedding('Muuse Aamina','2030-12-12','Mogadishu')})).wedding;const a2=(await req('/weddings',{token:a.token,method:'POST',status:201,body:wedding('Ahmed Hodan','2031-03-20','Hargeisa')})).wedding;const b1=(await req('/weddings',{token:b.token,method:'POST',status:201,body:wedding('Ali Hani','2031-06-05','Nairobi')})).wedding;pass('one customer creates two different weddings',a1.customer===a2.customer&&a1._id!==a2._id);const list=await req('/weddings',{token:a.token});pass('GET /weddings returns both owned weddings only',list.count===2&&list.weddings.every(w=>w.customer===a.user._id));await req(`/weddings/${a1._id}`,{token:b.token,status:404});await req(`/weddings/${b1._id}`,{token:a.token,status:404});pass('cross-customer single wedding access rejected');
await req(`/budget?weddingId=${a1._id}`,{token:a.token,method:'POST',status:201,body:{category:'Venue',title:'Wedding A Venue',plannedAmount:1000,actualAmount:200}});await req(`/guests?weddingId=${a1._id}`,{token:a.token,method:'POST',status:201,body:{firstName:'WeddingA',lastName:'Guest'}});await req(`/tasks?weddingId=${a1._id}`,{token:a.token,method:'POST',status:201,body:{title:'Wedding A Task'}});
let [budgetA,guestsA,tasksA,budgetA2,guestsA2,tasksA2]=await Promise.all([req(`/budget?weddingId=${a1._id}`,{token:a.token}),req(`/guests?weddingId=${a1._id}`,{token:a.token}),req(`/tasks?weddingId=${a1._id}`,{token:a.token}),req(`/budget?weddingId=${a2._id}`,{token:a.token}),req(`/guests?weddingId=${a2._id}`,{token:a.token}),req(`/tasks?weddingId=${a2._id}`,{token:a.token})]);pass('Wedding A data does not appear in Wedding B',budgetA.budget.items.length===1&&guestsA.guests.length===1&&tasksA.tasks.length===1&&budgetA2.budget.items.length===0&&guestsA2.guests.length===0&&tasksA2.tasks.length===0);
await req(`/budget?weddingId=${a2._id}`,{token:a.token,method:'POST',status:201,body:{category:'Catering',title:'Wedding B Catering',plannedAmount:2000,actualAmount:500}});await req(`/guests?weddingId=${a2._id}`,{token:a.token,method:'POST',status:201,body:{firstName:'WeddingB',lastName:'Guest'}});await req(`/tasks?weddingId=${a2._id}`,{token:a.token,method:'POST',status:201,body:{title:'Wedding B Task'}});[budgetA,guestsA,tasksA]=await Promise.all([req(`/budget?weddingId=${a1._id}`,{token:a.token}),req(`/guests?weddingId=${a1._id}`,{token:a.token}),req(`/tasks?weddingId=${a1._id}`,{token:a.token})]);pass('switching back preserves Wedding A original data',budgetA.budget.items[0].title==='Wedding A Venue'&&guestsA.guests[0].firstName==='WeddingA'&&tasksA.tasks[0].title==='Wedding A Task');
await req(`/budget?weddingId=${a1._id}`,{token:b.token,status:404});await req(`/guests?weddingId=${a2._id}`,{token:b.token,status:404});await req(`/tasks?weddingId=${b1._id}`,{token:a.token,status:404});pass('Budget, Guests, and Tasks reject foreign wedding IDs');console.log(JSON.stringify({success:true,passed},null,2));}
finally{await mongoose.connect(process.env.MONGO_URI,{dbName:'wedding_planning'});const weddings=await Wedding.find({customer:{$in:users}}).distinct('_id');await Promise.all([BudgetItem.deleteMany({wedding:{$in:weddings}}),Guest.deleteMany({wedding:{$in:weddings}}),Task.deleteMany({wedding:{$in:weddings}}),Wedding.deleteMany({_id:{$in:weddings}}),User.deleteMany({_id:{$in:users}})]);await mongoose.disconnect();}
