import api from './api.js';
export const getVendors = (params) => api.get('/vendors', { params }).then((r) => r.data);
export const getVendor = (id) => api.get(`/vendors/${id}`).then((r) => r.data);
export const getVendorProfile = () => api.get('/vendors/me/profile').then((r) => r.data);
export const saveVendorProfile = (data) => api.put('/vendors/me/profile', data).then((r) => r.data);
export const getBookings = (weddingId) => api.get('/bookings', { params: { weddingId } }).then((r) => r.data);
export const createBooking = (data, weddingId) => api.post('/bookings', { ...data, weddingId }).then((r) => r.data);
export const bookHall = (data, weddingId) => api.post('/bookings/hall', data, {
  headers: { 'X-Wedding-Id': weddingId || '' },
}).then((r) => r.data);
export const cancelBooking = (id) => api.patch(`/bookings/${id}/cancel`).then((r) => r.data);
export const getVendorBookings = () => api.get('/vendor/bookings').then((r) => r.data);
export const updateVendorBooking = (id, data) => api.patch(`/vendor/bookings/${id}/status`, data).then((r) => r.data);
export const getInvitations = (weddingId) => api.get('/invitations', { params: { weddingId } }).then((r) => r.data);
export const createInvitation = (data, weddingId) => api.post('/invitations', { ...data, weddingId }).then((r) => r.data);
export const updateInvitation = (id, data) => api.patch(`/invitations/${id}`, data).then((r) => r.data);
export const deleteInvitation = (id) => api.delete(`/invitations/${id}`).then((r) => r.data);
export const getPublicInvitation = (token) => api.get(`/public/invitations/${token}`).then((r) => r.data);
export const submitRsvp = (token, data) => api.post(`/public/rsvp/${token}`, data).then((r) => r.data);
export const getConversations = (weddingId) => api.get('/conversations', { params: { weddingId } }).then((r) => r.data);
export const createConversation = (data, weddingId) => api.post('/conversations', { ...data, weddingId }).then((r) => r.data);
export const getMessages = (id) => api.get(`/conversations/${id}/messages`).then((r) => r.data);
export const sendMessage = (id, text) => api.post(`/conversations/${id}/messages`, { text }).then((r) => r.data);
export const getReport = (weddingId) => api.get('/reports', { params: { weddingId } }).then((r) => r.data);
export const updateAccount = (data) => api.patch('/auth/me', data).then((r) => r.data);
export const changePassword = (data) => api.patch('/auth/password', data).then((r) => r.data);
export const getListings = (params) => api.get('/listings', { params }).then((r) => r.data);
export const getMarketplaceListings = (params) => api.get('/marketplace/listings', { params }).then((r) => r.data);
export const getListing = (id) => api.get(`/listings/${id}`).then((r) => r.data);
export const getSelections = (weddingId) => api.get('/selections', { params: { weddingId } }).then((r) => r.data);
export const createSelection = (data, weddingId) => api.post('/selections', { ...data, weddingId }).then((r) => r.data);
export const updateSelection = (id, data) => api.patch(`/selections/${id}`, data).then((r) => r.data);
export const getPayments = (weddingId) => api.get('/payments', { params: { weddingId } }).then((r) => r.data);
export const createPayment = (data) => api.post('/payments', data).then((r) => r.data);
export const initiateWaafiPayment = (data) => api.post('/payments/waafi/initiate', data).then((r) => r.data);
export const getPaymentStatus = (id) => api.get(`/payments/${id}/status`).then((r) => r.data);
export const confirmTestPayment = (id) => api.post(`/payments/${id}/confirm-test`).then((r) => r.data);
export const getNotifications = () => api.get('/notifications').then((r) => r.data);
export const markNotificationRead = (id) => api.patch(`/notifications/${id}/read`).then((r) => r.data);
export const markAllNotificationsRead = () => api.patch('/notifications/read-all').then((r) => r.data);
export const getAdminNotificationRecipients = () => api.get('/admin/notification-recipients').then((r) => r.data);
export const sendAdminNotification = (data) => api.post('/admin/notifications/send', data).then((r) => r.data);
export const getAdminNotifications = (params) => api.get('/admin/notifications', { params }).then((r) => r.data);
export const getAdminNotification = (id) => api.get(`/admin/notifications/${id}`).then((r) => r.data);
export const archiveAdminNotification = (id) => api.patch(`/admin/notifications/${id}/archive`).then((r) => r.data);
export const getAdminAnnouncements = () => api.get('/admin/announcements').then((r) => r.data);
export const createAdminAnnouncement = (data) => api.post('/admin/announcements', data).then((r) => r.data);
export const updateAdminAnnouncement = (id, data) => api.patch(`/admin/announcements/${id}`, data).then((r) => r.data);
export const getTimeline = (weddingId) => api.get('/timeline', { params: { weddingId } }).then((r) => r.data);
export const createTimelineEvent = (data, weddingId) => api.post('/timeline', { ...data, weddingId }).then((r) => r.data);
export const updateTimelineEvent = (id, data) => api.patch(`/timeline/${id}`, data).then((r) => r.data);
export const deleteTimelineEvent = (id) => api.delete(`/timeline/${id}`).then((r) => r.data);
export const previewInvitation = (weddingId) => api.get('/invitations/preview', { params: { weddingId } }).then((r) => r.data);
export const updateInvitationTemplate = (data, weddingId) => api.patch('/invitations/template', { ...data, weddingId }).then((r) => r.data);
export const getVendorReports = () => api.get('/vendor/reports').then((r) => r.data);
export const getPlannerReports = () => api.get('/planner/reports').then((r) => r.data);
export const getAdminReports = () => api.get('/admin/reports').then((r) => r.data);
export const getMyListings = () => api.get('/vendor/listings').then((r) => r.data);
export const createListing = (data) => api.post('/vendor/listings', data).then((r) => r.data);
export const updateListing = (id, data) => api.patch(`/vendor/listings/${id}`, data).then((r) => r.data);
export const deactivateListing = (id) => api.delete(`/vendor/listings/${id}`).then((r) => r.data);
export const uploadListingImages = (files) => {
  const formData = new FormData();
  files.forEach((file) => formData.append('images', file));
  return api.post('/vendor/listings/upload-images', formData, {
    timeout: 60000,
  }).then((r) => r.data);
};
export const getVendorOrders = () => api.get('/vendor/orders').then((r) => r.data);
export const getOrders = (params) => api.get('/orders', { params }).then((r) => r.data);
export const getVendorPayments = () => api.get('/vendor/payments').then((r) => r.data);
export const createAppointment = (data, weddingId) => api.post('/appointments', { ...data, weddingId }).then((r) => r.data);
export const createRental = (data, weddingId) => api.post('/rentals', { ...data, weddingId }).then((r) => r.data);
export const getListingAvailability = (id, params) => api.get(`/listings/${id}/availability`, { params }).then((r) => r.data);
