import api from './api.js';

export const getAdminDashboard = () => api.get('/admin/dashboard').then((r) => r.data);
export const getAdminUsers = (params) => api.get('/admin/users', { params }).then((r) => r.data);
export const createAdminUser = (data) => api.post('/admin/users', data).then((r) => r.data);
export const updateAdminUser = (id, data) => api.patch(`/admin/users/${id}`, data).then((r) => r.data);
export const deleteAdminUser = (id) => api.delete(`/admin/users/${id}`).then((r) => r.data);
export const getAdminCustomers = (params) => api.get('/admin/customers', { params }).then((r) => r.data);
export const getAdminCustomer = (id) => api.get(`/admin/customers/${id}`).then((r) => r.data);
export const getAdminPlanners = (params) => api.get('/admin/planners', { params }).then((r) => r.data);
export const getAdminPlanner = (id) => api.get(`/admin/planners/${id}`).then((r) => r.data);
export const getAdminWeddings = () => api.get('/admin/weddings').then((r) => r.data);
export const createAdminWedding = (data) => api.post('/admin/weddings', data).then((r) => r.data);
export const assignPlanner = (id, planner) => api.patch(`/admin/weddings/${id}/planner`, { planner }).then((r) => r.data);
export const getAdminVendors = (params) => api.get('/admin/vendors', { params }).then((r) => r.data);
export const getAdminVendor = (id) => api.get(`/admin/vendors/${id}`).then((r) => r.data);
export const updateAdminVendor = (id, data) => api.patch(`/admin/vendors/${id}`, data).then((r) => r.data);
export const getAdminBookings = (params) => api.get('/admin/bookings', { params }).then((r) => r.data);
export const getAdminBooking = (id) => api.get(`/admin/bookings/${encodeURIComponent(id)}`).then((r) => r.data);
export const updateAdminBookingStatus = (id, status) => api.patch(`/admin/bookings/${encodeURIComponent(id)}/status`, { status }).then((r) => r.data);
export const cancelAdminBooking = (id) => api.patch(`/admin/bookings/${encodeURIComponent(id)}/cancel`).then((r) => r.data);
export const getAdminPayments = () => api.get('/admin/payments').then((r) => r.data);
export const getAdminSelections = () => api.get('/admin/selections').then((r) => r.data);
export const getAdminWedding = (id) => api.get(`/admin/weddings/${id}`).then((r) => r.data);
export const getAdminOrders = () => api.get('/admin/orders').then((r) => r.data);
export const getAdminHallBookings = () => api.get('/admin/hall-bookings').then((r) => r.data);
export const getAssignedWedding = (id) => api.get(`/planner/weddings/${id}`).then((r) => r.data);
export const getAdminVenues = (params) => api.get('/admin/venues', { params }).then((r) => r.data);
export const getAdminVenue = (id) => api.get(`/admin/venues/${id}`).then((r) => r.data);
export const createAdminVenue = (data) => api.post('/admin/venues', data).then((r) => r.data);
export const updateAdminVenue = (id, data) => api.patch(`/admin/venues/${id}`, data).then((r) => r.data);
export const linkAdminVenueVendor = (id, vendor) => api.patch(`/admin/venues/${id}/vendor`, { vendor }).then((r) => r.data);
export const createAdminHall = (id, data) => api.post(`/admin/venues/${id}/halls`, data).then((r) => r.data);
export const updateAdminHall = (id, data) => api.patch(`/admin/halls/${id}`, data).then((r) => r.data);
export const getAdminListings = () => api.get('/admin/listings').then((r) => r.data);
export const updateAdminListing = (id, data) => api.patch(`/admin/listings/${id}`, data).then((r) => r.data);
