import api from './api.js';

export const getVenues = (params) => api.get('/venues', { params }).then((r) => r.data);
export const getPublicVenues = (params) => api.get('/public/venues', { params }).then((r) => r.data);
export const getHalls = (params) => api.get('/halls', { params }).then((r) => r.data);
export const getVenue = (id) => api.get(`/venues/${id}`).then((r) => r.data);
export const getVenueAvailability = (id, date, context = {}) => api.get(`/venues/${id}/availability`, { params: { date, ...context } }).then((r) => r.data);
export const getHall = (id) => api.get(`/halls/${id}`).then((r) => r.data);
export const getHallAvailability = (id, date, context = {}) => api.get(`/halls/${id}/availability`, { params: { date, ...context } }).then((r) => r.data);
export const getHallBookings = (weddingId) => api.get('/hall-bookings', { params: { weddingId } }).then((r) => r.data);
export const holdHallBooking = (data, weddingId) => api.post('/hall-bookings/hold', { ...data, weddingId }).then((r) => r.data);
export const requestHallQuote = (data, weddingId) => api.post('/hall-quotes/request', { ...data, weddingId }).then((r) => r.data);
export const listHallQuotes = (params) => api.get('/hall-quotes', { params }).then((r) => r.data);
export const getHallQuote = (id) => api.get(`/hall-quotes/${id}`).then((r) => r.data);
export const submitHallQuote = (id, data) => api.patch(`/hall-quotes/${id}/submit`, data).then((r) => r.data);
export const acceptHallQuote = (id, data = {}) => api.post(`/hall-quotes/${id}/accept`, data).then((r) => r.data);
export const rejectHallQuote = (id) => api.post(`/hall-quotes/${id}/reject`).then((r) => r.data);
export const cancelHallQuote = (id) => api.post(`/hall-quotes/${id}/cancel`).then((r) => r.data);
export const replaceHallBooking = (data, weddingId) => api.post('/hall-bookings/replace', { ...data, weddingId }).then((r) => r.data);
export const confirmHallBooking = (bookingId) => api.post('/hall-bookings/confirm', { bookingId }).then((r) => r.data);
export const cancelHallBooking = (id) => api.patch(`/hall-bookings/${id}/cancel`).then((r) => r.data);
export const getListingAvailability = (id, params) => api.get(`/listings/${id}/availability`, { params }).then((r) => r.data);
export const createAppointment = (data, weddingId) => api.post('/appointments', { ...data, weddingId }).then((r) => r.data);
export const createRental = (data, weddingId) => api.post('/rentals', { ...data, weddingId }).then((r) => r.data);
export const getOrders = (params) => api.get('/orders', { params }).then((r) => r.data);
export const getVendorVenues = () => api.get('/vendor/venues').then((r) => r.data);
export const createVendorVenue = (data) => api.post('/vendor/venues', data).then((r) => r.data);
export const updateVendorVenue = (id, data) => api.patch(`/vendor/venues/${id}`, data).then((r) => r.data);
export const createVendorHall = (venueId, data) => api.post(`/vendor/venues/${venueId}/halls`, data).then((r) => r.data);
export const updateVendorHall = (id, data) => api.patch(`/vendor/halls/${id}`, data).then((r) => r.data);
export const saveHallSlots = (id, slots) => api.put(`/vendor/halls/${id}/slots`, { slots }).then((r) => r.data);
export const getVendorHallBookings = () => api.get('/vendor/hall-bookings').then((r) => r.data);
export const getVendorOperationalOrders = () => api.get('/vendor/orders').then((r) => r.data);
export const updateVendorOrder = (id, data) => api.patch(`/vendor/orders/${id}`, data).then((r) => r.data);
export const getPlannerDashboard = () => api.get('/planner/dashboard').then((r) => r.data);
export const getPlannerWedding = (id) => api.get(`/planner/weddings/${id}`).then((r) => r.data);
export const createPlannerTask = (weddingId, data) => api.post(`/planner/weddings/${weddingId}/tasks`, data).then((r) => r.data);
export const updatePlannerTask = (taskId, data) => api.patch(`/planner/tasks/${taskId}`, data).then((r) => r.data);
export const getVendorTasks = () => api.get('/vendor/tasks').then((r) => r.data);
export const updateVendorTask = (id, data) => api.patch(`/vendor/tasks/${id}`, data).then((r) => r.data);
