import { useState } from 'react';
import { labelTaskValue, taskCategories } from '../../utils/taskOptions.js';

const inputClass = 'mt-2 w-full rounded-xl border border-stone-200 bg-white px-4 py-3 outline-none transition focus:border-brand-400 focus:ring-2 focus:ring-brand-100';
function toDateInput(value) { return value ? new Date(value).toISOString().slice(0, 10) : ''; }

function TaskForm({ task, weddingDate, submitting, error, onSubmit, onCancel, hideHeader = false }) {
  const [form, setForm] = useState(task ? { title: task.title, description: task.description || '', category: task.category, priority: task.priority, dueDate: toDateInput(task.dueDate), status: task.status } : { title: '', description: '', category: 'other', priority: 'medium', dueDate: '', status: 'pending' });
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  async function handleSubmit(event) { event.preventDefault(); await onSubmit({ ...form, title: form.title.trim(), description: form.description.trim(), dueDate: form.dueDate || null }); }
  return <form onSubmit={handleSubmit} className="space-y-5">{hideHeader ? null : <div><h2 className="font-display text-2xl font-semibold text-stone-900">{task ? 'Edit Task' : 'Add Task'}</h2><p className="mt-1 text-sm text-stone-500">Keep every wedding detail organized and on schedule.</p></div>}{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<label className="block text-sm font-medium text-stone-700">Task Title<input required maxLength="160" name="title" value={form.title} onChange={update} className={inputClass} /></label><label className="block text-sm font-medium text-stone-700">Description <span className="font-normal text-stone-400">(optional)</span><textarea rows="3" maxLength="1000" name="description" value={form.description} onChange={update} className={`${inputClass} resize-none`} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-stone-700">Category<select name="category" value={form.category} onChange={update} className={inputClass}>{taskCategories.map((item) => <option key={item} value={item}>{labelTaskValue(item)}</option>)}</select></label><label className="text-sm font-medium text-stone-700">Priority<select name="priority" value={form.priority} onChange={update} className={inputClass}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label className="text-sm font-medium text-stone-700">Due Date <span className="font-normal text-stone-400">(optional)</span><input type="date" name="dueDate" max={weddingDate ? toDateInput(weddingDate) : undefined} value={form.dueDate} onChange={update} className={inputClass} /></label>{task && <label className="text-sm font-medium text-stone-700">Status<select name="status" value={form.status} onChange={update} className={inputClass}><option value="pending">Pending</option><option value="in_progress">In Progress</option><option value="completed">Completed</option></select></label>}</div><div className="flex flex-col-reverse gap-3 border-t pt-5 sm:flex-row sm:justify-end"><button type="button" onClick={onCancel} className="rounded-full border px-6 py-3 text-sm font-semibold text-stone-600 hover:bg-stone-50">Cancel</button><button disabled={submitting || !form.title.trim()} className="rounded-full bg-brand-600 px-7 py-3 text-sm font-semibold text-white hover:bg-brand-700 disabled:opacity-60">{submitting ? 'Saving...' : task ? 'Save Changes' : 'Add Task'}</button></div></form>;
}
export default TaskForm;
