import { FiCheck, FiEdit2, FiRotateCcw, FiTrash2 } from 'react-icons/fi';
import { formatTaskDate, isTaskOverdue } from '../../utils/filterTasks.js';
import { labelTaskValue } from '../../utils/taskOptions.js';

const priorityClasses = { high: 'bg-red-50 text-red-700', medium: 'bg-amber-50 text-amber-700', low: 'bg-emerald-50 text-emerald-700' };
const statusClasses = { pending: 'bg-stone-100 text-stone-600', in_progress: 'bg-blue-50 text-blue-700', completed: 'bg-emerald-50 text-emerald-700' };
function Actions({ task, busy, onEdit, onStatus, onDelete }) { return <div className="flex flex-wrap items-center gap-2"><button disabled={busy} onClick={() => onStatus(task, task.status === 'completed' ? 'pending' : 'completed')} className="inline-flex items-center gap-1.5 rounded-lg border px-3 py-2 text-xs font-semibold text-stone-600 hover:bg-stone-50 disabled:opacity-50">{task.status === 'completed' ? <FiRotateCcw /> : <FiCheck />}{task.status === 'completed' ? 'Reopen' : 'Complete'}</button><button aria-label={`Edit ${task.title}`} disabled={busy} onClick={() => onEdit(task)} className="rounded-lg border p-2.5 text-stone-500 hover:bg-stone-50"><FiEdit2 /></button><button aria-label={`Delete ${task.title}`} disabled={busy} onClick={() => onDelete(task)} className="rounded-lg border border-red-100 p-2.5 text-red-500 hover:bg-red-50"><FiTrash2 /></button></div>; }
function TaskList({ tasks, busyId, onEdit, onStatus, onDelete }) {
  const content = (task, mobile = false) => { const overdue = isTaskOverdue(task); return mobile ? <article key={task._id} className="p-5"><div className="flex items-start justify-between gap-3"><div><p className={`font-semibold ${task.status === 'completed' ? 'text-stone-400 line-through' : 'text-stone-800'}`}>{task.title}</p><p className="mt-1 text-sm text-stone-500">{labelTaskValue(task.category)}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${priorityClasses[task.priority]}`}>{labelTaskValue(task.priority)}</span></div>{task.description && <p className="mt-3 text-sm leading-6 text-stone-500">{task.description}</p>}<div className="my-4 flex flex-wrap gap-2 text-xs"><span className={`rounded-full px-2.5 py-1 font-semibold ${statusClasses[task.status]}`}>{labelTaskValue(task.status)}</span><span className={`rounded-full bg-stone-50 px-2.5 py-1 ${overdue ? 'font-semibold text-red-600' : 'text-stone-600'}`}>{formatTaskDate(task.dueDate)}{overdue ? ' - Overdue' : ''}</span></div><Actions task={task} busy={busyId === task._id} onEdit={onEdit} onStatus={onStatus} onDelete={onDelete} /></article> : <tr key={task._id} className={task.status === 'completed' ? 'bg-stone-50/40' : ''}><td className="max-w-xs px-5 py-4"><p className={`font-semibold ${task.status === 'completed' ? 'text-stone-400 line-through' : 'text-stone-800'}`}>{task.title}</p>{task.description && <p className="mt-1 truncate text-xs text-stone-500">{task.description}</p>}</td><td className="px-4 py-4 text-stone-600">{labelTaskValue(task.category)}</td><td className={`whitespace-nowrap px-4 py-4 ${overdue ? 'font-semibold text-red-600' : 'text-stone-600'}`}>{formatTaskDate(task.dueDate)}{overdue && <span className="ml-2 rounded-full bg-red-50 px-2 py-1 text-[10px] uppercase">Overdue</span>}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${priorityClasses[task.priority]}`}>{labelTaskValue(task.priority)}</span></td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusClasses[task.status]}`}>{labelTaskValue(task.status)}</span></td><td className="px-4 py-4"><Actions task={task} busy={busyId === task._id} onEdit={onEdit} onStatus={onStatus} onDelete={onDelete} /></td></tr>; };
  return <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="bg-stone-50 text-xs uppercase tracking-wide text-stone-500"><tr><th className="px-5 py-4">Task</th><th className="px-4 py-4">Category</th><th className="px-4 py-4">Due Date</th><th className="px-4 py-4">Priority</th><th className="px-4 py-4">Status</th><th className="px-4 py-4">Actions</th></tr></thead><tbody className="divide-y divide-stone-100">{tasks.map((task) => content(task))}</tbody></table></div><div className="divide-y divide-stone-100 md:hidden">{tasks.map((task) => content(task, true))}</div></>;
}
export default TaskList;
