import { Router } from 'express';
import healthRoutes from './healthRoutes.js';
import authRoutes from './authRoutes.js';
import weddingRoutes from './weddingRoutes.js';
import budgetRoutes from './budgetRoutes.js';
import guestRoutes from './guestRoutes.js';
import taskRoutes from './taskRoutes.js';
import vendorRoutes from './vendorRoutes.js';
import bookingRoutes from './bookingRoutes.js';
import vendorBookingRoutes from './vendorBookingRoutes.js';
import invitationRoutes from './invitationRoutes.js';
import publicInvitationRoutes from './publicInvitationRoutes.js';
import conversationRoutes from './conversationRoutes.js';
import reportRoutes from './reportRoutes.js';
import adminRoutes from './adminRoutes.js';
import plannerRoutes from './plannerRoutes.js';
import listingRoutes from './listingRoutes.js';
import marketplaceRoutes from './marketplaceRoutes.js';
import selectionRoutes from './selectionRoutes.js';
import paymentRoutes from './paymentRoutes.js';
import publicRoutes from './publicRoutes.js';
import venueRoutes from './venueRoutes.js';
import hallRoutes from './hallRoutes.js';
import hallBookingRoutes from './hallBookingRoutes.js';
import hallQuoteRoutes from './hallQuoteRoutes.js';
import orderRoutes from './orderRoutes.js';
import scheduleRoutes from './scheduleRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import timelineRoutes from './timelineRoutes.js';
import cartRoutes from './cartRoutes.js';
import weddingMemberRoutes from './weddingMemberRoutes.js';

const router = Router();
router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/weddings', weddingRoutes);
router.use('/budget', budgetRoutes);
router.use('/guests', guestRoutes);
router.use('/tasks', taskRoutes);
router.use('/vendors', vendorRoutes);
router.use('/bookings', bookingRoutes);
router.use('/vendor', vendorBookingRoutes);
router.use('/invitations', invitationRoutes);
router.use('/public', publicInvitationRoutes);
router.use('/conversations', conversationRoutes);
router.use('/reports', reportRoutes);
router.use('/admin', adminRoutes);
router.use('/planner', plannerRoutes);
router.use('/listings', listingRoutes);
router.use('/marketplace', marketplaceRoutes);
router.use('/selections', selectionRoutes);
router.use('/payments', paymentRoutes);
router.use('/public', publicRoutes);
router.use('/venues', venueRoutes);
router.use('/halls', hallRoutes);
router.use('/hall-bookings', hallBookingRoutes);
router.use('/hall-quotes', hallQuoteRoutes);
router.use('/orders', orderRoutes);
router.use('/notifications', notificationRoutes);
router.use('/timeline', timelineRoutes);
router.use('/cart', cartRoutes);
router.use('/wedding-members', weddingMemberRoutes);
router.use('/', scheduleRoutes);

export default router;
